FROM nvidia/cuda:11.7.0-cudnn8-runtime-ubuntu22.04

ENV TZ=Europe
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

################################
# Install apt-get Requirements #
################################

# General
RUN apt-get update && \
    apt-get install -y python3-pip cmake zlib1g-dev python3-tk \ 
    # Boost libraries
    libboost-all-dev \
    # Scipy requirements
    libblas-dev liblapack-dev libatlas-base-dev gfortran \
    dpkg-dev build-essential libjpeg-dev  libtiff-dev libnotify-dev \
    ffmpeg swig  \
    curl software-properties-common \
    build-essential \
    nasm tar libbz2-dev libgtk2.0-dev cmake git \
    unzip wget && \
    apt-get clean autoclean && \
    apt-get autoremove -y

################################
# Install Python 3.7           #
################################

RUN DEBIAN_FRONTEND=noninteractive add-apt-repository --yes ppa:deadsnakes/ppa && apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes python3.7 python3.7-dev python3.7-venv


############################
# Install Pip Requirements #
############################

RUN curl -o /usr/local/bin/patchelf https://s3-us-west-2.amazonaws.com/openai-sci-artifacts/manual-builds/patchelf_0.9_amd64.elf \
    && chmod +x /usr/local/bin/patchelf

COPY . /root/src
WORKDIR /root/src
RUN python3.7 -m venv --copies /root/venv && . /root/venv/bin/activate && pip install .
